<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="7.3.1" />
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="7.3.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\ControlDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Features\Commands\AddFeature\AddCompanyFeature\" />
    <Folder Include="Services\Features\Commands\AddFeature\AddCategoryFeature\" />
    <Folder Include="Services\Features\Commands\AddFeature\AddProductFeature\" />
    <Folder Include="Services\Features\Commands\AddFeature\AddMachineFeature\" />
    <Folder Include="Services\Features\Commands\EditFeature\EditCategoryFeature\" />
    <Folder Include="Services\Features\Commands\EditFeature\EditCompanyFeature\" />
    <Folder Include="Services\Features\Commands\EditFeature\EditMachineFeature\" />
    <Folder Include="Services\Features\Commands\EditFeature\EditProductFeature\" />
  </ItemGroup>

</Project>
